= Concert API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:

[[overview]]
== Overview

[[resources]]
== Resources

[[resources-concert]]
=== Concert API

[[resources-concert-create]]
==== 콘서트 생성

operation::createConcert[snippets='http-request,http-response,request-fields,response-fields']

[[resources-concert-get]]
==== 콘서트 조회

operation::getConcert[snippets='http-request,http-response,path-parameters,response-fields']

[[resources-concert-search]]
==== 콘서트 검색

operation::searchConcerts[snippets='http-request,http-response,request-fields,response-fields']

[[resources-member]]
=== Member API

[[resources-member-create]]
==== 멤버 생성

operation::createMember[snippets='http-request,http-response,request-fields,response-fields']

[[resources-member-get]]
==== 멤버 조회

operation::getMember[snippets='http-request,http-response,path-parameters,response-fields']

[[resources-point]]
=== Point API

[[resources-point-charge]]
==== 포인트 충전

operation::charge[snippets='http-request,http-response,request-fields,response-fields']

[[resources-point-use]]
==== 포인트 사용

operation::use[snippets='http-request,http-response,request-fields,response-fields']

[[resources-auth]]
=== Auth API

[[resources-auth-login]]
==== 로그인

operation::login[snippets='http-request,http-response,request-fields,response-fields']